package fields

// Stores which options configure the chain. Those options are exclusive to each other
var ChainOptions = map[string]struct{}{
	"chain":    {},
	"test":     {},
	"testnet4": {},
	"signet":   {},
}

// Available sections to configure chain-specific options
var AvailableSections map[string]string = map[string]string{
	"main":     "Options for mainnet",
	"test":     "Options for testnet3",
	"testnet4": "Options for testnet4",
	"signet":   "Options for signet",
	"regtest":  "Options for regtest",
}

var AllowedDuplicateOptions = map[string]struct{}{
	"addnode":        {},
	"whitebind":      {},
	"whitelist":      {},
	"wallet":         {},
	"debug":          {},
	"debugexclude":   {},
	"signetseednode": {},
	"rpcallowip":     {},
	"rpcauth":        {},
	"rpcbind":        {},
}

var TopicForOption = map[string]string{
	"alertnotify":                  "Options",
	"allowignoredconf":             "Options",
	"assumevalid":                  "Options",
	"blockfilterindex":             "Options",
	"blocknotify":                  "Options",
	"blockreconstructionextratxn":  "Options",
	"blocksdir":                    "Options",
	"blocksonly":                   "Options",
	"blocksxor":                    "Options",
	"coinstatsindex":               "Options",
	"conf":                         "Options",
	"daemon":                       "Options",
	"daemonwait":                   "Options",
	"datadir":                      "Options",
	"dbcache":                      "Options",
	"debuglogfile":                 "Options",
	"includeconf":                  "Options",
	"loadblock":                    "Options",
	"maxmempool":                   "Options",
	"maxorphantx":                  "Options",
	"mempoolexpiry":                "Options",
	"par":                          "Options",
	"persistmempool":               "Options",
	"persistmempoolv1":             "Options",
	"pid":                          "Options",
	"prune":                        "Options",
	"reindex":                      "Options",
	"reindex-chainstate":           "Options",
	"settings":                     "Options",
	"shutdownnotify":               "Options",
	"startupnotify":                "Options",
	"txindex":                      "Options",
	"version":                      "Options",
	"addnode":                      "Connection options",
	"asmap":                        "Connection options",
	"bantime":                      "Connection options",
	"bind":                         "Connection options",
	"cjdnsreachable":               "Connection options",
	"connect":                      "Connection options",
	"discover":                     "Connection options",
	"dns":                          "Connection options",
	"dnsseed":                      "Connection options",
	"externalip":                   "Connection options",
	"fixedseeds":                   "Connection options",
	"forcednsseed":                 "Connection options",
	"i2pacceptincoming":            "Connection options",
	"i2psam":                       "Connection options",
	"listen":                       "Connection options",
	"listenonion":                  "Connection options",
	"maxconnections":               "Connection options",
	"maxreceivebuffer":             "Connection options",
	"maxsendbuffer":                "Connection options",
	"maxuploadtarget":              "Connection options",
	"natpmp":                       "Connection options",
	"networkactive":                "Connection options",
	"onion":                        "Connection options",
	"onlynet":                      "Connection options",
	"peerblockfilters":             "Connection options",
	"peerbloomfilters":             "Connection options",
	"port":                         "Connection options",
	"proxy":                        "Connection options",
	"proxyrandomize":               "Connection options",
	"seednode":                     "Connection options",
	"timeout":                      "Connection options",
	"torcontrol":                   "Connection options",
	"torpassword":                  "Connection options",
	"v2transport":                  "Connection options",
	"whitebind":                    "Connection options",
	"whitelist":                    "Connection options",
	"whitelistforcerelay":          "Connection options",
	"whitelistrelay":               "Connection options",
	"addresstype":                  "Wallet options",
	"avoidpartialspends":           "Wallet options",
	"changetype":                   "Wallet options",
	"consolidatefeerate":           "Wallet options",
	"disablewallet":                "Wallet options",
	"discardfee":                   "Wallet options",
	"fallbackfee":                  "Wallet options",
	"keypool":                      "Wallet options",
	"maxapsfee":                    "Wallet options",
	"mintxfee":                     "Wallet options",
	"paytxfee":                     "Wallet options",
	"signer":                       "Wallet options",
	"spendzeroconfchange":          "Wallet options",
	"txconfirmtarget":              "Wallet options",
	"wallet":                       "Wallet options",
	"walletbroadcast":              "Wallet options",
	"walletdir":                    "Wallet options",
	"walletnotify":                 "Wallet options",
	"walletrbf":                    "Wallet options",
	"zmqpubhashblock":              "ZeroMQ notification options",
	"zmqpubhashblockhwm":           "ZeroMQ notification options",
	"zmqpubhashtx":                 "ZeroMQ notification options",
	"zmqpubhashtxhwm":              "ZeroMQ notification options",
	"zmqpubrawblock":               "ZeroMQ notification options",
	"zmqpubrawblockhwm":            "ZeroMQ notification options",
	"zmqpubrawtx":                  "ZeroMQ notification options",
	"zmqpubrawtxhwm":               "ZeroMQ notification options",
	"zmqpubsequence":               "ZeroMQ notification options",
	"zmqpubsequencehwm":            "ZeroMQ notification options",
	"debug":                        "Debugging/Testing options",
	"debugexclude":                 "Debugging/Testing options",
	"logips":                       "Debugging/Testing options",
	"loglevelalways":               "Debugging/Testing options",
	"logsourcelocations":           "Debugging/Testing options",
	"logthreadnames":               "Debugging/Testing options",
	"logtimestamps":                "Debugging/Testing options",
	"maxtxfee":                     "Debugging/Testing options",
	"printtoconsole":               "Debugging/Testing options",
	"shrinkdebugfile":              "Debugging/Testing options",
	"uacomment":                    "Debugging/Testing options",
	"chain":                        "Chain selection options",
	"signet":                       "Chain selection options",
	"signetchallenge":              "Chain selection options",
	"signetseednode":               "Chain selection options",
	"testnet":                      "Chain selection options",
	"testnet4":                     "Chain selection options",
	"bytespersigop":                "Node relay options",
	"datacarrier":                  "Node relay options",
	"datacarriersize":              "Node relay options",
	"minrelaytxfee":                "Node relay options",
	"permitbaremultisig":           "Node relay options",
	"blockmaxweight":               "Block creation options",
	"blockmintxfee":                "Block creation options",
	"blockreservedweight":          "Block creation options",
	"rest":                         "RPC server options",
	"rpcallowip":                   "RPC server options",
	"rpcauth":                      "RPC server options",
	"rpcbind":                      "RPC server options",
	"rpccookiefile":                "RPC server options",
	"rpccookieperms":               "RPC server options",
	"rpcpassword":                  "RPC server options",
	"rpcport":                      "RPC server options",
	"rpcthreads":                   "RPC server options",
	"rpcuser":                      "RPC server options",
	"rpcwhitelist":                 "RPC server options",
	"rpcwhitelistdefault":          "RPC server options",
	"server":                       "RPC server options",
}
