name: Run Go tests

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v27
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check if project can be linted
        run: nix develop --command bash -c "just lint" && git diff --exit-code

      - name: Check if antlr parsers are up to date
        run: nix develop --command bash -c "just update-antlr-parsers" && git diff --exit-code

      - name: Check Nix flake
        run: nix flake check

      - name: Build app
        run: nix develop --command bash -c "cd server && go build"

      - name: Build VS Code extension
        run: nix build .#vs-code-extension

      - name: Upload VS Code extension
        uses: actions/upload-artifact@v4
        with:
          name: vs-code-extension
          path: result/config-lsp-*.vsix

